spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/encode
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

server:
  error:
    include-message: always

jwt:
  jwt-key: "5Fr8DCJ+4PnJ9uoUFc/SPPYwKSJCAsZxtr2uU3Ky4JU="
